### ISSUE TITLE
"mvn package" error

### ISSUE THREAD

**Issue by mtorabirad** [ISI-TechknAcq/techknacq-core#5]
mvn package gives me this error

BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.868s
[INFO] Finished at: Mon Mar 29 09:30:01 UTC 2021
[INFO] Final Memory: 7M/118M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project techknacq-core: Could not resolve dependencies for project edu.isi.techknacq:techknacq-core:jar:0.3-SNAPSHOT: Failed to collect dependencies for [com.fasterxml.jackson.core:jackson-core:jar:2.5.0 (compile), me.lizier:infodynamics:jar:1.3 (compile), org.lemurproject:kstem:jar:3.4 (compile), com.google.code.gson:gson:jar:2.5 (compile), org.apache.lucene:lucene-core:jar:2.3.2 (compile), com.googlecode.json-simple:json-simple:jar:1.1.1 (compile)]: Failed to read artifact descriptor for me.lizier:infodynamics:jar:1.3: Could not transfer artifact me.lizier:infodynamics:pom:1.3 from/to isi.nexus.server.thirdparty (http://colo-pm2.isi.edu:8081/nexus/content/repositories/thirdparty/): colo-pm2.isi.edu: Unknown host colo-pm2.isi.edu -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

--------------------------
My guess is that the urls in the pom.xml file are not valid anymore. For example, this url 
http://colo-pm2.isi.edu:8081/nexus/content/repositories/thirdparty/

Any comments?
@jgordon

**Comment by jgordon** [comment]
This may be quite difficult to fix properly. The developers are no longer affiliated with ISI, where that repository was hosted. 

I'm not a Java developer, but I expect you could switch to some other public repository and get all of the packages except for `edu.isi.techknacq-core`, which is available in source form from https://github.com/ISI-TechKnAcq/techknacq-core

Any thoughts, @GullyAPCBurns ?

**Comment by mtorabirad** [comment]
@jgordon thank you for the reply. If you guys give me some guidance, I would be more than happy to contribute to making this repo live again.
